version: '3.8'

services:
  zap:
    image: "ghcr.io/zaproxy/zaproxy:latest"
    command: zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=fookey
    links:
      - juice-shop
    ports:
      - "8090:8090"

  juice-shop:
    image: "bkimminich/juice-shop"
    ports:
      - "3000:3000"

  mysql:
    image: "mysql:8.0"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mini-dast
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "33060:3306"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "MYsECRETf0Raccess"
      POSTGRES_DB: "zascans_db"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
