@baseUrl = http://localhost:9000

# @name allscans
GET {{baseUrl}}/list HTTP/1.1
Authorization: Basic YWRtaW46cGFzc3dvcmQ=
###

# @name createScanIntree
POST  {{baseUrl}}/create
Content-Type: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

{
    "urls": ["http://juice-shop:3000"]
}
###

# @name startScan
POST  {{baseUrl}}/start
Content-Type: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

{
    "urls": ["http://juice-shop:3000"]
}
###

# @name results
GET {{baseUrl}}/results/0 HTTP/1.1
Authorization: Basic YWRtaW46cGFzc3dvcmQ=
###