basePath: /
definitions:
  controllers.CreateSiteRequest:
    properties:
      urls:
        items:
          type: string
        type: array
    type: object
  controllers.StartScanRequest:
    properties:
      urls:
        items:
          type: string
        type: array
    type: object
  services.ScanResponse:
    properties:
      scan:
        type: string
    type: object
host: localhost:9000
info:
  contact: {}
  description: A simple REST API to integration a ZAProxy vulnerability scans
  title: API ZapScan Integration
  version: "1.0"
paths:
  /create:
    post:
      consumes:
      - application/json
      description: Create Site for new scan
      operationId: create-scan
      parameters:
      - description: query params
        in: body
        name: urls
        required: true
        schema:
          $ref: '#/definitions/controllers.CreateSiteRequest'
      - description: Authorization header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.ScanResponse'
        "500":
          description: Internal Server Error
      security:
      - BasicAuth: []
      summary: Create Site
      tags:
      - create-scans
  /list:
    get:
      consumes:
      - application/json
      description: List All existing scansIds
      operationId: list-all
      parameters:
      - description: Authorization header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      security:
      - BasicAuth: []
      summary: List all scans
      tags:
      - get-scans
  /results/:scanId:
    get:
      consumes:
      - application/json
      description: Show scan results by scanId
      operationId: show-results
      parameters:
      - description: Scan ID
        in: path
        name: scanId
        required: true
        type: string
      - description: Authorization header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      security:
      - BasicAuth: []
      summary: Show results by scanId
      tags:
      - get-scans
  /start:
    post:
      consumes:
      - application/json
      description: Start a new active scan
      operationId: post-scans
      parameters:
      - description: query params
        in: body
        name: urls
        required: true
        schema:
          $ref: '#/definitions/controllers.StartScanRequest'
      - description: Authorization header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.ScanResponse'
        "500":
          description: Internal Server Error
      security:
      - BasicAuth: []
      summary: Start Scan
      tags:
      - start-scans
swagger: "2.0"
