basePath: /
host: localhost:9000
info:
  contact: {}
  description: A simple REST API to integration a ZAProxy vulnerability scans
  title: API ZapScan Integration
  version: "1.0"
paths: {}
swagger: "2.0"
